theme = 'mytheme'
languageCode = 'en'
defaultContentLanguage = 'en'
pygmentsUseClasses = false
baseURL = 'https://jandolezal.github.io/'

[Taxonomies]
tag = 'tags'

[markup.highlight]
codeFences = true
noClasses = true
style = 'monokailight'

[params]
mainSections = ['posts']
images = ['profile_photo.jpg']
github = 'https://www.github.com/jandolezal'
linkedin = 'https://www.linkedin.com/in/janfdolezal'
twitter = 'https://www.twitter.com/jandolezal'
# socialImage = 'profile_photo_rounded.jpg'

[languages]
[languages.en]
title = 'Jan Dolezal'
author = 'Jan Dolezal'
images = ['profile_photo.jpg']
description = 'Blog mostly about my GitHub projects and such.'
[languages.en.params]
postName = 'Blog'
tagsName = 'Tags'
[languages.en.menu]
[[languages.en.menu.main]]
name = 'Home'
url = '/'
weight = 1
[[languages.en.menu.main]]
name = 'About'
url = '/about'
weight = 0
[[languages.en.menu.main]]
name = 'Tags'
url = '/tags'
weight = 0

[languages.cs]
title = 'Jan Doležal'
author = 'Jan Doležal'
description = 'Blog hlavně o mých projektech na GitHubu'
images = ['profile_photo.jpg']
[languages.cs.params]
postName = 'Blog'
tagsName = 'Štítky'
[languages.cs.menu]
[[languages.cs.menu.main]]
name = 'Domů'
url = '/'
weight = 1
[[languages.cs.menu.main]]
name = 'O stránce'
url = '/o-strance'
weight = 0
[[languages.cs.menu.main]]
name = 'Štítky'
url = '/tags'
weight = 0
